# Autogenerated config.py
config.load_autoconfig(False)

# Aliases
c.aliases = {'q': 'quit', 'w': 'session-save', 'wq': 'quit --save'}

c.auto_save.session = True
c.session.default_name = 'default'

# --- UI Layout Changes ---
# Move tabs to the right side and make them vertical
c.tabs.position = 'right'
c.tabs.width = '10%' # Adjust width as needed
c.tabs.padding = {'top': 10, 'bottom': 10, 'left': 10, 'right': 10}
c.tabs.show = 'never'

# General Settings
c.downloads.location.directory = '~/Downloads'
c.url.default_page = 'https://duckduckgo.com/'
c.url.start_pages = 'https://duckduckgo.com/'

# Search Engines
c.url.searchengines = {
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'am': 'https://www.amazon.com/s?k={}',
    'aw': 'https://wiki.archlinux.org/?search={}',
    'goog': 'https://www.google.com/search?q={}',
    're': 'https://www.reddit.com/r/{}',
    'wiki': 'https://en.wikipedia.org/wiki/{}',
    'yt': 'https://www.youtube.com/results?search_query={}'
}

# --- Gruvbox Color Palette ---
# Backgrounds: #282828 (dark), #3c3836 (lighter)
# Foregrounds: #ebdbb2 (light), #d5c4a1 (muted)
# Accents:     #fb4934 (red), #b8bb26 (green), #fabd2f (yellow), #83a598 (blue), #d3869b (purple), #8ec07c (aqua)

# Completion Widget
c.colors.completion.fg = '#ebdbb2'
c.colors.completion.odd.bg = '#282828'
c.colors.completion.even.bg = '#3c3836'
c.colors.completion.category.fg = '#fabd2f'
c.colors.completion.category.bg = '#282828'
c.colors.completion.item.selected.fg = '#282828'
c.colors.completion.item.selected.bg = '#ebdbb2'
c.colors.completion.item.selected.match.fg = '#fb4934'
c.colors.completion.match.fg = '#fb4934'

# Statusbar
c.colors.statusbar.normal.bg = '#282828'
c.colors.statusbar.normal.fg = '#ebdbb2'
c.colors.statusbar.insert.bg = '#b8bb26'
c.colors.statusbar.insert.fg = '#282828'
c.colors.statusbar.command.bg = '#3c3836'
c.colors.statusbar.command.fg = '#ebdbb2'

# Tabs (Vertical)
c.colors.tabs.bar.bg = '#1d2021'
c.colors.tabs.odd.bg = '#3c3836'
c.colors.tabs.odd.fg = '#ebdbb2'
c.colors.tabs.even.bg = '#3c3836'
c.colors.tabs.even.fg = '#ebdbb2'
c.colors.tabs.selected.odd.bg = '#282828'
c.colors.tabs.selected.odd.fg = '#fabd2f'
c.colors.tabs.selected.even.bg = '#282828'
c.colors.tabs.selected.even.fg = '#fabd2f'

# Hints
c.colors.hints.bg = '#fabd2f'
c.colors.hints.fg = '#282828'
c.colors.hints.match.fg = '#ebdbb2'

# --- Fonts ---
c.fonts.default_family = '"Segoe UI Variable", "Segoe UI", sans-serif'
c.fonts.default_size = '11pt'
c.zoom.default = '125%'

# --- Key Bindings ---
config.bind('M', 'hint links spawn mpv {hint-url}')
config.bind('t', 'set-cmd-text -s :open -t')
config.bind('xb', 'config-cycle statusbar.show always never')
config.bind('xt', 'config-cycle tabs.show always never')
config.bind('xx', 'config-cycle tabs.show always never;; config-cycle statusbar.show always never')
config.bind('xd', 'config-cycle colors.webpage.darkmode.enabled true false')

# User Agent & Domain Specific Settings
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0', 'https://accounts.google.com/*')
config.set('content.javascript.enabled', True, 'qute://*/*')

# --- Security ---
# Disable features that leak data or enable tracking
c.content.webrtc_ip_handling_policy = 'disable-non-proxied-udp'  # Prevent WebRTC IP leaks
c.content.canvas_reading = False        # Block canvas fingerprinting
c.content.geolocation = False           # Block geolocation
c.content.notifications.enabled = False # Block notification requests
c.content.media.audio_capture = False   # Block mic
c.content.media.video_capture = False   # Block camera
c.content.media.audio_video_capture = False
c.content.autoplay = False              # No autoplay (minor fingerprinting vector)
c.content.cookies.accept = 'no-3rdparty'  # Block third-party cookies


# DNS-over-HTTPS (use your preferred resolver)
c.content.dns_prefetch = False          # Disable DNS prefetching

# Headers
c.content.headers.do_not_track = True
c.content.headers.referer = 'same-domain'  # Only send referrer to same domain

# SSL/TLS
c.content.tls.certificate_errors = 'block'  # Block on TLS errors (default, make explicit)

# --- Anonymity / Fingerprinting ---
# Spoof a generic, common user agent globally (blends in better than a unique one)
c.content.headers.user_agent = (
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
    'AppleWebKit/537.36 (KHTML, like Gecko) '
    'Chrome/148.0.0.0 Safari/537.36'
)

# --- Content Blocking ---
# Enable ad/tracker blocking (requires filter lists to be configured)
c.content.blocking.enabled = True
c.content.blocking.method = 'both'  # Use both hosts + adblock methods
c.content.blocking.adblock.lists = [
    'https://easylist.to/easylist/easylist.txt',
    'https://easylist.to/easylist/easyprivacy.txt',
    'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt',
    'https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt',
    'https://www.i2p2.de/hosts.txt',  # optional
]

# --- JavaScript (balance usability vs security) ---
# If you want JS off by default, uncomment:
# c.content.javascript.enabled = False
# config.set('content.javascript.enabled', True, '*://duckduckgo.com/*')
# config.set('content.javascript.enabled', True, '*://github.com/*')
# ... whitelist as needed

# --- Downloads ---
c.downloads.prevent_mixed_content = True  # Block HTTP downloads from HTTPS pages

# --- Misc ---
c.content.site_specific_quirks.enabled = False  # Reduces fingerprint surface

